# -*- coding: utf-8 -*-
"""AI-Blog-Generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tR8Z0Q5eQ-9-DtIBOhvRRKqEzCLPMRrS
"""

import google.generativeai as genai
import gradio as gr

genai.configure(api_key="YOUR_API_KEY")

model = genai.GenerativeModel("gemini-2.5-flash")


def generate_blog(topic, audience, language, tone, terminology, words):

    prompt = f"""
Write a well-structured blog of approximately {words} words.

Topic: {topic}

Target Audience: {audience}

Language: {language}

Tone: {tone}

Terminology Level: {terminology}

Include:

- Catchy Title
- Introduction
- Main Content
- Fun Facts
- Advantages
- Conclusion
"""

    response = model.generate_content(prompt)

    return response.text


demo = gr.Interface(
    fn=generate_blog,

    inputs=[
        gr.Textbox(label="Topic"),

        gr.Textbox(label="Audience"),

        gr.Dropdown(
            ["Telugu", "Hindi", "English", "Kannada", "Marathi"],
            label="Language"
        ),

        gr.Dropdown(
            ["Professional", "Casual", "Funny", "Technical", "Inspirational", "Sarcastic"],
            label="Tone"
        ),

        gr.Dropdown(
            ["Simple", "Moderate", "Complex"],
            label="Terminology"
        ),

        gr.Slider(
            minimum=100,
            maximum=1200,
            value=500,
            label="Word Count"
        )
    ],

    outputs=gr.Markdown(),

    title="📝 AI Blog Generator",

    description="Generate blogs in multiple languages and writing styles using Google Gemini."
)

demo.launch(debug=True)